# Generated by Django 5.1 on 2024-08-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField()),
                ('vocation', models.CharField(max_length=50)),
                ('world', models.CharField(db_index=True, max_length=50)),
                ('other_characters', models.CharField(max_length=1000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.account')),
            ],
        ),
    ]
