# Generated by Django 5.1 on 2024-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(related_name='discord_users', to='bot.character')),
            ],
        ),
    ]
