# Generated by Django 5.1 on 2024-08-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_discorduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='accountid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.discorduser'),
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='discord_id',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='User',
            field=models.CharField(default='Unknown User', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='DiscordUserAndCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.character')),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.discorduser')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
